# Generated by Django 5.1.15 on 2026-06-08 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestadocita',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.mecanico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='motocicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.motocicleta'),
        ),
        migrations.AddField(
            model_name='cambioestadocita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='serviciocita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita'),
        ),
        migrations.AddField(
            model_name='serviciocita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(related_name='citas', through='citas.ServicioCita', to='servicios.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciocita',
            unique_together={('cita', 'servicio')},
        ),
    ]
