# Generated by Django 5.1.15 on 2026-06-07 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='citas.cita')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
