# Generated by Django 5.1.15 on 2026-09-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='observaciones_cierre',
            field=models.TextField(blank=True, help_text='Notas del administrador al finalizar el servicio (V2SCRUM-24).', verbose_name='Observaciones de cierre'),
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos_usados', to='citas.cita')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_citas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Repuesto usado',
                'verbose_name_plural': 'Repuestos usados',
                'unique_together': {('cita', 'producto')},
            },
        ),
    ]