# Generated by Django 5.1.15 on 2026-10-04 04:10

import apps.citas.models
import django.db.models.deletion
from django.db import migrations, models


ESTADOS = [
    # codigo, nombre, tipo, color, orden, permite_cancelar
    ('pendiente',  'Pendiente',  'inicio',     '#ffb000', 1, True),
    ('confirmada', 'Confirmada', 'proceso',    '#00e5ff', 2, True),
    ('en_proceso', 'En proceso', 'proceso',    '#c084fc', 3, False),
    ('completada', 'Completada', 'completado', '#00ff66', 4, False),
    ('cancelada',  'Cancelada',  'cancelado',  '#ff3b5c', 5, False),
]


def cargar_estados(apps, schema_editor):
    """Pasa los 5 estados que estaban fijos en el código al catálogo, con el mismo código."""
    EstadoCita = apps.get_model('citas', 'EstadoCita')
    for codigo, nombre, tipo, color, orden, permite_cancelar in ESTADOS:
        EstadoCita.objects.create(
            codigo=codigo,
            nombre=nombre,
            tipo=tipo,
            color=color,
            orden=orden,
            permite_cancelar=permite_cancelar,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_repuestousado_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio'), ('proceso', 'Proceso'), ('completado', 'Finalización – completado'), ('cancelado', 'Finalización – cancelado')], default='proceso', max_length=20)),
                ('color', models.CharField(default='#c084fc', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Se asigna solo al crear el estado.')),
                ('permite_cancelar', models.BooleanField(default=False, help_text='El cliente puede cancelar o reagendar la cita mientras esté en este estado.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado de cita',
                'verbose_name_plural': 'Estados de cita',
                'ordering': ['orden', 'nombre'],
            },
        ),
        # los estados se cargan antes de convertir los campos en FK, así las citas existentes ya apuntan a un estado válido
        migrations.RunPython(cargar_estados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cambioestadocita',
            name='estado_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_desde', to='citas.estadocita'),
        ),
        migrations.AlterField(
            model_name='cambioestadocita',
            name='estado_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_hacia', to='citas.estadocita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(default=apps.citas.models.estado_inicial, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.estadocita'),
        ),
    ]
