# Generated by Django 5.1.15 on 2026-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Día de la semana')),
                ('abierto', models.BooleanField(default=True, help_text='Si el taller atiende este día.', verbose_name='Atiende')),
                ('hora_apertura', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
            ],
            options={
                'verbose_name': 'Horario del taller',
                'verbose_name_plural': 'Horarios del taller',
                'ordering': ['dia_semana'],
            },
        ),
    ]
