# Generated by Django 5.1.15 on 2026-06-08 05:48

import apps.usuarios.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dui', models.CharField(help_text='Formato: 00000000-0', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de DUI inválido. Debe ser 00000000-0.', regex='^\\d{8}-\\d$')], verbose_name='DUI')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(help_text='Formato: 0000-0000', max_length=9, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Debe ser 0000-0000.', regex='^\\d{4}-\\d{4}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Marcar como inactivo en lugar de eliminar.', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al panel administrativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido', 'nombre'],
            },
            managers=[
                ('objects', apps.usuarios.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', apps.usuarios.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(choices=[('mecanica_general', 'Mecánica general'), ('electrico', 'Sistema eléctrico'), ('motor', 'Motor'), ('suspension_frenos', 'Suspensión y frenos')], max_length=50)),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', apps.usuarios.managers.UsuarioManager()),
            ],
        ),
    ]
