# Generated by Django 5.1.15 on 2026-05-27 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('placa', models.CharField(help_text='Formato: M-####', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Debe ser M-#### (ej. M-1234).', regex='^M-\\d{4}$')])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(help_text='Año de fabricación.', validators=[django.core.validators.MinValueValidator(1980)])),
                ('color', models.CharField(max_length=30)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Marcar como inactiva en lugar de eliminar.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motocicletas', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
