# Generated by Django 5.1.15 on 2026-10-04 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='placa',
            field=models.CharField(help_text='Formato: L-#### (una letra y 4 dígitos)', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Debe ser una letra, guión y 4 dígitos (ej. M-1234).', regex='^[A-Z]-\\d{4}$')]),
        ),
    ]
